module Agreement exposing (agreement)


agreement =
    """
## SERVICES SUBSCRIPTION TERMS AND CONDITIONS

These Services Subscription TERMS AND CONDITIONS (this &quot; **Agreement**&quot;), dated as of the date Customer affirmatively agrees hereto (the &quot; **Effective Date**&quot;), by checking the box set forth on Service Provider’s website (or as otherwise indicated by Customer’s request for the Services) and is by and between MyREassurance, Inc., a Colorado corporation, with offices located at 8827 Cactus Flower Way, Highlands Ranch, CO 80126 (&quot; **Service Provider**&quot;) and you, an individual with an address is located as set forth in the account information you have completed (&quot; **Customer**&quot; and together with Service Provider, the &quot; **Parties**&quot;, and each a &quot; **Party**&quot;).

WHEREAS, Service Provider runs a subscription based real estate service that allows a customer to sell two (2) residential properties (commercial properties are specifically excluded) located in the Denver, Colorado metro area, within a five (5) year period without paying a listing agent commission but with the full level of service from a top real estate agent (the &quot; **Services**&quot;); and

WHEREAS, Customer desires to retain Service Provider to provide such Services, and Service Provider is willing to perform such Services under the terms and conditions hereinafter set forth;

NOW, THEREFORE, in consideration of the mutual covenants and agreements hereinafter set forth and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, Service Provider and Customer agree as follows:

1. __Services__. Subject to and conditioned on Customer&#39;s payment of Fees and the restrictions set forth herein, Service Provider shall provide the Services to Customer during the Term of this Agreement:
    - 1.1 Beginning on a date which is six (6) months from the Effective Date of this Agreement, Customer may list real property for sale with Service Provider pursuant to the terms set forth herein;
    - 1.2 Service Provider will waive its listing agent commission with respect to two (2) real property listings during the five (5) year Term of this Agreement; provided, Customer will be entitled to list its first property for sale no earlier than the six (6) months from the Effective Date of this Agreement; and provided further, Customer will be entitled to list its second real property for sale no earlier than twelve (12) months following the listing of the first real property sale;
    - 1.3 Each Customer will enter into an Exclusive Right to Sell Listing Contract (using the most recent version of the Colorado Division of Real Estate Commission approved form) with Service Provider prior to Service Provider being required to list any real property pursuant to this Agreement.
    - 1.4 Subject to execution by the Customer and transferee of a Notice of Transfer (which Customer may request from Service Provider), Customer may transfer one or both of its listing rights under this Agreement to a third person during the Term. Notwithstanding any transfer, Customer shall remain fully liable for the Fees required during the Term.
    - 1.5 If a Customer (or any transferee) terminates a property listing, the Customer has no right to re-list the same or a substitute property in lieu of such listing and instead will lose their listing right with respect to such property. Customer is limited to two (2) property listings under this Agreement.
    - 1.6 During the Term, Customer agrees that if it intends to or does purchase any real estate property for which Customer uses a real estate agent, Customer will: (a) if such property is located in the Denver, Colorado metro area, engage Service Provider as its real estate agent at its standard broker fee, or (b) if the property is located outside of the Denver, Colorado metro area, engage the real estate agent referred to Customer by Service Provider at its standard broker fee.
2. __Fees and Expenses__.
    - 2.1. _Fees_. In consideration of the provision of the Services by the Service Provider and the rights granted to Customer under this Agreement, Customer shall pay the fees set out below by credit card payment:
        - (a). _Initial Set-Up Fee_. Customer shall pay a non-refundable initial set-up fee of $199 to Service Provider, plus the first monthly Fee (defined below) upon execution of this Agreement.  Service Provider will not begin any Services hereunder until such initial set-up fee and monthly Fee is paid.
        - (b). _Monthly Fee_. For the Services to be performed hereunder, Customer shall pay to Service Provider a monthly fee of $99 (the “ __Fee__ ”) beginning on the first day of the month following the Effective Date of this Agreement and continuing through the Term of this Agreement. 
        - (c). _Fees Due for Full Term_.  For avoidance of doubt, Customer shall be responsible for the Fees due hereunder for each of the 60 months of the Term, regardless of whether Service Provider has listed one or two properties prior to the expiration of the Term.
        - (d). _Prepayment_. At the time of the closing of the second real property listing made by Service Provider for the Customer pursuant to this Agreement, the Customer will pay in full the amount of the Fee to be paid pursuant to Section 2.1(b) from the closing date of the second real property listing through expiration of the Term.
    - 2.2 _Payment Method_. Customer shall pay the monthly Fees via the payment methods that Service Provider may make available to Customer, and such payments will be set up for automatic monthly payments. Customer authorizes Service Provider to charge Customer&#39;s form of payment on the first day of each month during the Term for the monthly Fee. If Customer&#39;s form of payment expires during the Term Customer will promptly provide Service Provider with a valid form of payment. All payments will be made on-line via the Service Providers on-line web portal which shall be provided to Customer upon initial account set-up.
    - 2.3 _Taxes_. Customer shall be responsible for all sales, use, and excise taxes, and any other similar taxes, duties, and charges of any kind imposed by any federal, state, or local governmental entity on any amounts payable by Customer hereunder; provided, that, in no event shall Customer pay or be responsible for any taxes imposed on, or regarding, Service Provider&#39;s income, revenues, gross receipts, personnel, or real or personal property or other assets.
    - 2.4 _Late Fee_. All late payments shall bear interest at the lesser of the rate of ten percent (10%) per month or the highest rate permissible under applicable law, calculated daily and compounded monthly. Customer shall also reimburse Service Provider for all costs incurred in collecting any late payments, including, without limitation, attorneys&#39; fees.
    - 2.5 _Suspension_. In addition to all other remedies available under this Agreement or at law (which Service Provider does not waive by the exercise of any rights hereunder), Service Provider shall be entitled to suspend the provision of any Services if Customer fails to pay any amounts when due hereunder if Customer fails to pay within five (5) days from receipt of a suspension notice.
3. __Term, Termination, and Survival__
    - 3.1 _Term_. This Agreement shall commence as of the Effective Date and shall continue thereafter until the five (5) year anniversary of the initial monthly Fee payment (&quot; **Term**&quot;), unless sooner terminated pursuant to 43.2 or 43.3.
    - 3.2 _Termination_. Either party may terminate this Agreement, effective upon written notice to the other party (the &quot; **Defaulting Party**&quot;), if the Defaulting Party: (a) materially breaches this Agreement, and such breach is incapable of cure, or with respect to a material breach capable of cure, the Defaulting Party does not cure such breach within 30 days after receipt of written notice of such breach; (b) becomes insolvent or admits its inability to pay its debts generally as they become due; (c) becomes subject, voluntarily or involuntarily, to any proceeding under any domestic or foreign bankruptcy or insolvency law, which is not fully stayed within seven business days or is not dismissed or vacated within 45 days after filing; (d) is dissolved or liquidated or takes any corporate action for such purpose; (e) makes a general assignment for the benefit of creditors; or (f) has a receiver, trustee, custodian, or similar agent appointed by order of any court of competent jurisdiction to take charge of or sell any material portion of its property or business.
    - 3.3 _Termination for Nonpayment_. Notwithstanding anything to the contrary in this Section, Service Provider may terminate this Agreement before the expiration date of the Term on written notice if Customer fails to pay any amount when due hereunder and such failure continues for ten (10) days after Service Provider&#39;s written notice to Customer of its intent to terminate. Termination of this Agreement for non-payment does not relieve Customer of its obligation to pay the monthly Fee for the remainder of the Term as required in Section 3.4 below.
    - 3.4 _Effect of Early Termination_. Upon early termination, if Customer has real property listed with Service Provider, Service Provider may remove such listing and all Services will terminate. Customer shall be responsible for paying Service Provider the monthly Fee for the remainder of the Term in full within ten (10) business days from any early termination of the Agreement.
    - 3.5 _Survival_. The rights and obligations of the Parties set forth in this Section 3 and in Sections 4-8, and any right or obligation of the Parties in this Agreement which, by its nature, should survive termination or expiration of this Agreement, will survive any such termination or expiration of this Agreement[, and with respect to Confidential Information that constitutes a trade secret under applicable law, the rights and obligations set forth in 55. hereof will survive such termination or expiration of this Agreement until, if ever, such Confidential Information loses its trade secret protection other than due to an act or omission of the Receiving Party.
4. __Intellectual Property__. All intellectual property rights, including copyrights, patents, patent disclosures, and inventions (whether patentable or not), trademarks, service marks, trade secrets, know-how, and other confidential information, trade dress, trade names, logos, corporate names, and domain names, together with all of the goodwill associated therewith, derivative works, and all other rights (collectively, &quot; **Intellectual Property Rights**&quot;) in and to all documents, work product, and other materials that are delivered to Customer under this Agreement or prepared by or on behalf of the Service Provider in the course of performing the Services (collectively, the &quot; **Deliverables**&quot;) except for any Confidential Information of Customer or customer materials shall be owned by Service Provider. Service Provider hereby grants Customer a license to use all Intellectual Property Rights in the Deliverables free of additional charge and on a non-exclusive, worldwide, non-transferable, non-sublicenseable, fully paid-up, royalty-free, and perpetual basis to the extent necessary to enable Customer to make reasonable use of the Deliverables and the Services.
5. __Confidentiality__. From time to time during the Term of this Agreement, either Party (as the &quot; **Disclosing Party**&quot;) may disclose or make available to the other Party (as the &quot; **Receiving Party**&quot;), non-public, proprietary, and confidential information of Disclosing Party, whether or not marked, designated, or otherwise identified as &quot;confidential&quot; (&quot; **Confidential Information**&quot;); provided, however, that Confidential Information does not include any information that: (a) is or becomes generally available to the public other than as a result of Receiving Party&#39;s breach of this 55.; (b) is or becomes available to the Receiving Party on a non-confidential basis from a third-party source, provided that such third party is not and was not prohibited from disclosing such Confidential Information; (c) was in Receiving Party&#39;s possession prior to Disclosing Party&#39;s disclosure hereunder; or (d) was or is independently developed by Receiving Party without using any Confidential Information. The Receiving Party shall: (x) protect and safeguard the confidentiality of the Disclosing Party&#39;s Confidential Information with at least the same degree of care as the Receiving Party would use to protect its own Confidential Information, but in no event with less than a commercially reasonable degree of care; (y) not use the Disclosing Party&#39;s Confidential Information, or permit it to be accessed or used, for any purpose other than to exercise its rights or perform its obligations under this Agreement; and (z) not disclose any such Confidential Information to any person or entity, except to the Receiving Party&#39;s agents who need to know the Confidential Information to assist the Receiving Party, or act on its behalf, to exercise its rights or perform its obligations under this Agreement.

If the Receiving Party is required by applicable law or legal process to disclose any Confidential Information, it shall, prior to making such disclosure, use commercially reasonable efforts to notify Disclosing Party of such requirements to afford Disclosing Party the opportunity to seek, at Disclosing Party&#39;s sole cost and expense, a protective order or other remedy.

As the violation of the provisions of Sections 4 or 5 of the Agreement would cause irreparable injury to the non-breaching party, and there is no adequate remedy at law for such violation, the non-breaching party shall have the right to seek specific performance or injunctive relief against the breaching party without the posting of a bond or other security. The remedies available with respect to the rights and obligations under this Agreement are cumulative, and this section shall not be construed to limit in any manner whatsoever any other rights or remedies that may be available for any breach of this Agreement.

6. __Limited Warranty__. Service Provider warrants that it shall perform the Services (a) using personnel of commercially reasonable skill, experience, and qualifications; and (b) in a timely, workmanlike, and professional manner in accordance with generally recognized industry standards for similar services. SERVICE PROVIDER (a) MAKES NO WARRANTIES EXCEPT FOR THOSE SET OUT ABOVE; AND (b) DISCLAIMS ALL OTHER WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Service Provider&#39;s sole and exclusive liability and Customer&#39;s sole and exclusive remedy for breach of the limited warranty set out in this Section shall be reperformance of the affected services.
7. __Limitation of Liability.__
    - 7.1 IN NO EVENT SHALL SERVICE PROVIDER BE LIABLE TO CUSTOMER OR TO ANY THIRD PARTY FOR ANY LOSS OF USE, REVENUE, OR PROFIT OR LOSS OF DATA OR DIMINUTION IN VALUE, OR FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, OR PUNITIVE DAMAGES WHETHER ARISING OUT OF BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, REGARDLESS OF WHETHER SUCH DAMAGE WAS FORESEEABLE AND WHETHER OR NOT SERVICE PROVIDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF ANY AGREED OR OTHER REMEDY OF ITS ESSENTIAL PURPOSE.
    - 7.2 IN NO EVENT SHALL SERVICE PROVIDER&#39;S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER ARISING OUT OF OR RELATED TO BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, EXCEED TWO (2) TIMES THE AGGREGATE AMOUNTS PAID TO SERVICE PROVIDER PURSUANT TO THIS AGREEMENT IN THE TWENTY-FOUR MONTH PERIOD PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
8. __General__.
    - 8.1 Each of the parties hereto shall use reasonable efforts to, from time to time at the request of the other party, furnish the other party such further information or assurances, execute and deliver such additional documents, instruments, and conveyances, and take such other actions and do such other things, as may be reasonably necessary to carry out the provisions of this Agreement and give effect to the transactions contemplated hereby.
    - 8.2 Each party shall deliver all communications in writing either in person, by certified or registered mail, return receipt requested and postage prepaid, by facsimile or email (with confirmation of transmission), or by recognized overnight courier service, and addressed to the other party at the addresses set forth above (or to such other address that the receiving party may designate from time to time in accordance with this Section). A valid notice is considered received as follows: (i) if delivered personally, it is considered received immediately; (ii) if delivered by email, it is considered received upon confirmation of transmission; (iii) if delivered by registered or certified mail (postage prepaid, return receipt requested), it is considered received upon receipt as indicated by the date on the signed receipt or (vi) if delivered by overnight service, it is considered received upon confirmation of delivery.
    - 8.3 This Agreement contains the entire understanding of the parties with respect to the subject matter hereof and supersedes all prior and contemporaneous written or oral understandings, agreements, representations, and warranties with respect to such subject matter.
    - 8.4 The invalidity, illegality, or unenforceability of any provision herein does not affect any other provision herein or the validity, legality, or enforceability of such provision in any other jurisdiction. Upon a determination that any term or provision is invalid, illegal, or unenforceable, the Parties shall negotiate in good faith to modify this Agreement to effect the original intent of the Parties as closely as possible in order that the transactions contemplated hereby be consummated as originally contemplated to the greatest extent possible.
    - 8.5 The parties may not amend this Agreement except by written instrument signed by the parties.
    - 8.6 No waiver of any right, remedy, power, or privilege under this Agreement (&quot;**Right(s)**&quot;) is effective unless contained in a writing signed by the party charged with such waiver. No failure to exercise, or delay in exercising, any Right operates as a waiver thereof. No single or partial exercise of any Right precludes any other or further exercise thereof or the exercise of any other Right.
    - 8.7 The Rights under this Agreement are cumulative and are in addition to any other rights and remedies available at law or in equity or otherwise; provided that, the parties intend that the remedy set out in Error: Reference source not found6 (Limited Warranty) is Customer&#39;s exclusive remedy for the Service Provider&#39;s breach of the limited warranty set out in Error: Reference source not found6 (Limited Warranty).
    - 8.8 Customer may not directly or indirectly assign, transfer, or delegate any of or all of its rights or obligations under this Agreement, voluntarily or involuntarily, including by change of control, merger (whether or not such party is the surviving entity), operation of law, or any other manner, without the prior written consent of the other party; except in a transfer permitted under Section 1.3. Any purported assignment or delegation in violation of this Section shall be null and void. Service Provider may assign any of its rights or delegate any of its obligations to any affiliate or to any person acquiring all or substantially all of Service Provider&#39;s assets without Customer&#39;s consent.
    - 8.9 This Agreement is binding upon and inures to the benefit of the parties and their respective successors and permitted assigns. Except for the parties, their successors and permitted assigns, there are no third-party beneficiaries under this Agreement.
    - 8.10 The relationship between the Parties is that of independent contractors. The details of the method and manner for performance of the Services by Service Provider shall be under its own control, Customer being interested only in the results thereof. The Service Provider shall be solely responsible for supervising, controlling and directing the details and manner of the completion of the Services. Nothing contained in this Agreement shall be construed as creating any agency, partnership, joint venture or other form of joint enterprise, employment, or fiduciary relationship between the Parties, and neither Party shall have authority to contract for or bind the other Party in any manner whatsoever.
    - 8.11 This Agreement and all matters arising out of or relating to this Agreement are governed by, and construed in accordance with, the laws of Colorado, (including its statutes of limitations and applicable state choice of law provision), without giving effect to any conflict of laws provisions thereof that would result in the application of the laws of a different jurisdiction. Either party shall institute any legal suit, action, or proceeding arising out of or relating to this Agreement in the federal or state courts in each case located in Arapahoe County, Colorado.
    - 8.12 Each Party acknowledges that any controversy that may arise under this Agreement, including exhibits, schedules, attachments, and appendices attached to this Agreement, is likely to involve complicated and difficult issues and, therefore, each such Party irrevocably and unconditionally waives any right it may have to a trial by jury in respect of any legal action arising out of or relating to this Agreement, including any exhibits, schedules, attachments, or appendices attached to this Agreement, or the transactions contemplated hereby.
    - 8.13 No Party shall be liable or responsible to the other Party, nor be deemed to have defaulted under or breached this Agreement, for any failure or delay in fulfilling or performing any term of this Agreement (except for any obligations of the Customer to make payments to Service Provider hereunder), when and to the extent such failure or delay is caused by or results from acts beyond the impacted party&#39;s (&quot; **Impacted Party**&quot;) control, including, without limitation, the following force majeure events (&quot;Force Majeure Event(s)&quot;): (a) acts of God; (b) flood, fire, earthquake, pandemics, epidemics or explosion; (c) war, invasion, hostilities (whether war is declared or not), terrorist threats or acts, riot or other civil unrest; (d) government order, law, or actions; (e) embargoes or blockades in effect on or after the date of this Agreement; (f) national or regional emergency; and (i) other events beyond the control of the Impacted Party.
    - 8.14 By checking the box set forth on Service Provider’s website (or as otherwise indicated by Customer’s request for the Services) Customer agrees to these Services Subscription Terms and Conditions (Agreement).  It is Customer’s responsibility to read and understand this Agreement.

"""
